// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTrace(arg1) {
  return window['go']['main']['App']['DeleteTrace'](arg1);
}

export function GetHistory(arg1, arg2) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2);
}

export function GetHostSuggestions() {
  return window['go']['main']['App']['GetHostSuggestions']();
}

export function GetTrace(arg1) {
  return window['go']['main']['App']['GetTrace'](arg1);
}

export function StartTraceroute(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTraceroute'](arg1, arg2, arg3);
}

export function StopTraceroute() {
  return window['go']['main']['App']['StopTraceroute']();
}
