// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function DeleteTrace(arg1:number):Promise<void>;

export function GetHistory(arg1:string,arg2:number):Promise<Array<db.TraceRecord>>;

export function GetHostSuggestions():Promise<Array<string>>;

export function GetTrace(arg1:number):Promise<Array<db.HopRecord>>;

export function StartTraceroute(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StopTraceroute():Promise<void>;
